/// Generated by Devgen 
/// DO NOT EDIT
///
/// (c) Koheron

#ifndef __DEVICES_TABLE_HPP__
#define __DEVICES_TABLE_HPP__

#include <array>

#define DEVICES_TABLE(ENTRY) \
{% for device in devices -%}
    {% if not loop.last -%}
        ENTRY( {{device.name}}, {{device.class_name}}, {{ device | list_operations(max_op_num) }} ) \
    {% else -%}
        ENTRY( {{device.name}}, {{device.class_name}}, {{ device | list_operations(max_op_num) }} )
    {% endif -%}
{% endfor -%}

/// Maximum number of operations
#define MAX_OP_NUM {{max_op_num}}

/// Devices #
typedef enum {
    NO_DEVICE,
    KSERVER,
    {% for device in devices -%}
    {{ device.name | upper }},
    {% endfor -%}
    device_num
} device_t;

constexpr auto DEVICES_JSON = "{{ json }}";

#endif // __DEVICES_TABLE_HPP__
