/// Generated by Devgen 
/// DO NOT EDIT
///
/// (c) Koheron

#ifndef __DEVICES_TABLE_HPP__
#define __DEVICES_TABLE_HPP__

#include <array>

using device_t = std::size_t;

constexpr device_t NO_DEVICE = 0;
constexpr device_t KSERVER = 1;
    {% for device in devices -%}
constexpr device_t {{ device.tag | upper }} = {{ device.id }};
    {% endfor -%}
constexpr device_t device_num = {{ devices|length + 2 }};

#endif // __DEVICES_TABLE_HPP__
