/// Generated by Devgen 
/// DO NOT EDIT
///
/// (c) Koheron

#ifndef __DEVICES_TABLE_HPP__
#define __DEVICES_TABLE_HPP__

#include <array>
#include <tuple>
#include <memory>

#include <core/string_utils.hpp>

using device_t = std::size_t;

template<class Dev> constexpr device_t dev_id_of;

class NoDevice;
template<> constexpr device_t dev_id_of<NoDevice> = 0;

class KServer;
template<> constexpr device_t dev_id_of<KServer> = 1;
{% for device in devices %}
class {{ device.objects[0]["type"] }};
template<> constexpr device_t dev_id_of<{{ device.objects[0]["type"] }}> = {{ device.id }};
{% endfor -%}

constexpr device_t device_num = {{ devices|length + 2 }};

constexpr auto devices_names = kserver::make_array(
    kserver::str_const("NoDevice"),
    kserver::str_const("KServer"),
{%- for device in devices -%}
{% if not loop.last %}
    kserver::str_const("{{ device.objects[0]['type'] }}"),
{%- else %}
    kserver::str_const("{{ device.objects[0]['type'] }}")
{%- endif %}
{%- endfor %}
);

// Devices are store as unique_ptr ensuring single
// instantiation of each device.

using devices_tuple_t = std::tuple<
{%- for device in devices -%}
{% if not loop.last -%}
 std::unique_ptr<{{ device.objects[0]['type'] }}>,
{%- else -%}
 std::unique_ptr<{{ device.objects[0]['type'] }}>
{%- endif -%}
{%- endfor -%}
>;

#endif // __DEVICES_TABLE_HPP__
