/// {{ device.class_name|lower }}.hpp
///
/// Generated by devgen.
/// DO NOT EDIT.
///
/// (c) Koheron 

#ifndef __{{ device.class_name|upper }}_HPP__
#define __{{ device.class_name|upper }}_HPP__

{% for include in device.includes -%}
#include "{{ include }}"
{% endfor -%}

#if KSERVER_HAS_THREADS
#include <mutex>
#endif

#include <core/kdevice.hpp>
#include <core/devices_manager.hpp>

namespace kserver {

class {{ device.class_name }} : public KDevice<{{ device.class_name }},{{ device.tag }}>
{
  public:
    const device_t kind = {{ device.tag }};
    enum { __kind = {{ device.tag }} };

  public:
#if KSERVER_HAS_DEVMEM
    {{ device.class_name }}(KServer* kserver, MemoryManager& dev_mem_)
#else
    {{ device.class_name }}(KServer* kserver)
#endif
    : KDevice<{{ device.class_name }},{{ device.tag }}>(kserver)
#if KSERVER_HAS_DEVMEM
    , dev_mem(dev_mem_)
#endif
    {% for object in device.objects -%}
#if KSERVER_HAS_DEVMEM
    , {{ object["name"] }}(dev_mem_)
#else
    , {{ object["name"] }}()
#endif
    {% endfor -%}
    {}

    enum Operation {
        {% for operation in device.operations -%}
        {{ operation['tag'] }} = {{ operation['id'] }},
        {% endfor -%}        
        {{ device.tag|lower }}_op_num
    };

#if KSERVER_HAS_THREADS
    std::mutex mutex;
#endif

#if KSERVER_HAS_DEVMEM
    MemoryManager& dev_mem;
#endif
    {% for object in device.objects -%}
    {{ object["type"] }} {{ object["name"] }};
    {% endfor -%}

{% for operation in device.operations -%}
struct Argument_{{ operation['name'] }} {
{%- macro print_param_line(arg) %}
        {{ arg["type"] }} {{ arg["name"]}};
{%- endmacro -%}
{% for arg in operation["arguments"] -%}
    {{ arg["type"] }} {{ arg["name"]}};
{% endfor -%}
} args_{{ operation['name'] }};

{% endfor -%}

}; // class KS_{{ device.tag|capitalize }}

} // namespace kserver

#endif //__{{ device.class_name|upper }}_HPP__

